### ISSUE TITLE
(Question) Relative Saturation

### ISSUE THREAD

**Issue by frostspanner** [ddnexus/Flat-Plat-Equilux#24]
In the equilux color palette, how is relative saturation defined? For instance if I took another color and wanted to put it at 60% relative saturation how would I do that?

**Comment by ddnexus** [comment]
Hi @frostspanner 
yours is a simple question that actually requires a quite complex answer.

The equilux concept is organizing colors in sets that have different hues (picked in the full continuos spectrum, but possibly equally spaced) but have simultaneously the same perceived brightness/lightness and the same perceived saturation.

That means that given an equilux set, if you totally desaturate the colors in it, they will result in an (ideally) indistinguishable common shade of gray. That means that they are all the same percieved brightness/lightness. However, that is only half of the requirement: the other half is the perceived saturation, i.e. how much "colored" or far from gray a color looks.

Now since a full saturated yellow and a full saturated blue for example have very different perceived brightness, in order to put a blue and a yellow in the same equilux set, you will have to pick very different "kinds" of blue and yellow. For example, given a certain medium brightness you will have to pick a quite "dark" yellow and a quite "light" blue in order to match their perceived brightness. Now if you move your target brightness up, you will soon find that the brighter possible blu will be very desaturated compared to the brighter possible yellow. If you go down the brightness you will find a similar situation when the darker yellow will become very unsaturated in order to match a quite saturated dark blue.

All this long description is to explain you that the widest possible equilux palette is a limited subset of the regular RGB colors available in a computer (especially limited in the saturation range), because they have to satisfy the same-brightness/same-saturation rule. Sets out of this range are not possible because there will be missing colors on one end or the other that cannot satisfy the rule.

Now we finally arrive to the answer. Relative saturation is the concept of saturation applied to the possible equilux palette. The 100% relative saturation is the maximum possible saturation of any set that can maintain the rule. That doesn't mean 100% saturation in the computer sense... but it is "relative" to what is possible in the set. So 60% relative saturation is a saturation that is 60% of the maximum possible saturation for the equilux spectrum.

The equilux color palette is currently created by a mix of Inkscape documents with various filtering and manual adjustments. I never got the time to properly write a formula to get the complete set of n equilux colors (or full spectrum) for any brightness and saturation, so the manual part is still tricky.
 
At the moment in order to determine a color of a particular hue which fits into the 60% saturated set I wouldn't have any formula to calculate it. However the rule is that it should be indistinguishable from a set of the same brightness, and it should not be perceived more "colored" or less colored from the other colors in the same 60% set.

I hope to find the time to write an equilux set generator / color picker to put online, but it currently have a low priority.

Hoping to have answered your question.

**Comment by frostspanner** [comment]
That's a great explanation. I assumed it was something along those lines from playing around on colorizer.org when I noticed the Y in YPrBr on colorizer.org was staying the same, but I couldn't figure out how to mix the colors. I'd love a formula some day, but of course it's low priority. For myself I think I've decided in the mean time to patch the theme with zenburn colors instead of making a whole palette anyhow.
