### ISSUE TITLE
Unreadable selected text when window focus out

### ISSUE THREAD

**Issue by Shiriaev** [ddnexus/Flat-Plat-Equilux#26]
Hello!

Thanks for awesome theme.
I find small bug, when browser window lost focus, selected text become unreadable.
You can find screenshot in attachment.
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
- Latest Equilux version
- Ubuntu 16.04 with default Unity and all updates installed
![2018-10-12 11_26_01-magento - oracle vm virtualbox](https://user-images.githubusercontent.com/8590020/46857557-dc43d900-ce11-11e8-91fb-28a7a5319073.png)

**Comment by ddnexus** [comment]
Hi @Shiriaev,
FF is known to give problems to dark themes, so it might be a general problem, not an Equilux one. Please, could you install Materia (the upstream of Equilux), select a dark theme and post a screenshot?
Thanks

**Comment by Shiriaev** [comment]
@ddnexus ,
Materia seems a little bit more readable

![2018-10-12 11_50_45-magento - oracle vm virtualbox](https://user-images.githubusercontent.com/8590020/46859051-5f1a6300-ce15-11e8-9dd7-6460d9ade0ea.png)

**Comment by ddnexus** [comment]
Yes, however that negative (white on gray) style is not supposed to appear. If you look at that page in Chrome for example, Materia and Equilux work very well. Actually, also my own FireFox looks well with Equilux, because I fixed it with a profile or user style (I don't remember).
Bottom line, it is just one of many FF issues with dark themes, not a theme issue. It must be fixed in FF itself.

I will post the stylesheet to fix it as soon I will have some time to search the file and post it here.

**Comment by Shiriaev** [comment]
Okay, thanks a lot for care, I will search for settings to fix this issue
