### ISSUE TITLE
[GTK3] Gedit pink search error

### ISSUE THREAD

**Issue by ghost** [ddnexus/Flat-Plat-Equilux#3]
Hello :)

So, as I said in a comment in issue #2 there's a little annoyance in Gedit.
Search box goes pink when it doesn't find related values with entered text.
I'm not against a bit of pink but it makes the light grey text unreadable.

Steps to reproduce:

- Open Gedit _(didn't try with other text editors)_
- Open a file in it
- Search _(CTRL+F)_ for something that doesn't exist in the file

Used latest themes from GitHub, both standard and compact variants.

Seems to be from this line in gtk*.css:
```
spinbutton.error:not(.vertical),
entry.error {
    [...]
    background-color: #dea8de;
    color: #bebebe;
    [...]
}

```
However I think it's better to keep the pink and instead change text color which is originally `#bebebe`.

Thank you!

___

![capture d ecran de 2017-11-07 06-51-08](https://user-images.githubusercontent.com/1771322/32479214-0f2f3812-c389-11e7-835b-96cc8285c781.png)

**Comment by ddnexus** [comment]
That's a bug. I will fix it in the next release. Thanks.

FYI it is using the $error_color instead of the $error_bg_color as a background. The foreground colors chosen from the equilux_palette have exactly the same percieved brightness of the text color (#bebebe), so they look as smooth on the eye as the regular text, however for that exact reason they are completely wrong used as bacgkround colors, as you can tell :).

**Comment by ghost** [comment]
Ok thank you for explanations :)

**Comment by ddnexus** [comment]
Update:
This is a more general problem than what I thought. Equilux uses 2 specific colors (one used as foreground and another darker when used as background) for error, warning, etc., while Materia (and it seems also GTK apps) use just one color that sometimes is used as background and sometimes as foreground.
In order to maintain the 2 colors feature which gives a lot smoother style to the UI, I will have to change the way a few mixins produce their output and that will cost some time :/

**Comment by ghost** [comment]
Changing text color only in the related part (see 1st post) couldn't be an easier option?

**Comment by ddnexus** [comment]
As I (unsuccessfully) tried to explain, it is a general problem of Equilux which probably affects also other apps. There is no "related part" limited to your specific problem. The fix could be changing the background color to the $error_bg_color (#734873 dark magenta as defined in Equilux), or not changing the background color and changing the text color to the $error_color (#dea8de light magenta with the same brightness of the text color).

I will work on this and get it fixed ASAP, but at this time it is still not clear what would be better, nor how to get it done at the theme level.

I suggest you to keep editing your css as you feel it fits until the theme will get the proper fix.
Thanks.

**Comment by ddnexus** [comment]
A clarification just in case you need it. 

The css file that you edited is the product of the scss files that run mixins (sort of functions which include conditions) in order to generate the actual css content. What you see in the css may or may not have a one-to-one relation with some part of some scss file. 

In that specific case there is a quite complex logic that determines what you see in the css file, so in order to change the small output that you would like to change you have to change the logic of the mixins so they will produce a different output. And by changing that logic you will most likely impact the output of a lot of other parts in the css files.

HTH

**Comment by ghost** [comment]
Yeah, sorry I understand the SCSS files and what they do, was just wondering if there was a way to only impact the faulty part but it seems complicated. Waiting for an official and clean solution, I'll keep editing the file.

Thank you!

**Comment by ddnexus** [comment]
Fixed in [equilux-v20171110](https://github.com/ddnexus/equilux-theme/releases/tag/equilux-v20171110)

**Comment by ghost** [comment]
Thank you!
