### ISSUE TITLE
Cinnamon Panel

### ISSUE THREAD

**Issue by psimacek** [ddnexus/Flat-Plat-Equilux#4]
Hi, 

firstly, thanks for **best theme I ever seen!** I use Cinnamon. Is possible to develop a theme for the cinnamon panel?

https://cinnamon-spices.linuxmint.com/themes

Thanks

Petr

**Comment by ddnexus** [comment]
Thanks for the thanks! :) 
I am not sure I understand your request. Do you mean something like just publishing the theme in that site or packaging it in a special format or something else specific for Cinnamon?

**Comment by ghost** [comment]
@ddnexus 
He's asking for a theme compatible with Cinnamon (mostly the panel+menu).
Materia doesn't seem to have one though, so you would have to make it from scratch.
However you have some examples in the link he provided, if you want to make one.

**Comment by psimacek** [comment]
Thanks again @DarthWound  :-) You're right.

**Comment by ddnexus** [comment]
ahhhh...

Sorry, but I don't use Cinnamon and I don't have much time playing around, so I am afraid there is no plan in that direction. However, if you or anybody wants to contribute, I will be happy to help.

**Comment by ghost** [comment]
Started to work on something a few hours ago, just to try, even installed a Cinnamon session for it.
Used Adapta Cinnamon theme as a base and Equilux palette. Assets are easy and quick to change.
The most time consuming part is the cinnamon.css file, but changing colors only should be enough.

I don't know if I'll have time to finish it though, as I don't have in my mind where colors should go and all that kind of stuff unlike ddnexus, I have to examine gnome-shell.css to adapt everything.

**Comment by ddnexus** [comment]
@DarthWound You good Samaritan!

Actually I am not so deeply familiar with the scss and css files as you might think. I used a more heuristic approach: mostly replacing colors at the origin (colors.scss) while mostly ignoring where they actually are applied in shell and apps. 

Your task is a lot more difficult since there is no style file in the original theme referring to the Cinnamon panel and menu, so a heuristic approach would be a lot less heuristic :)

**Comment by ghost** [comment]
Currently I work a lot, at night, without the possibility to bring my laptop, and during daytime I sleep and my brain is almost dead :D so I can't promise anything but if I can I'll try to finish it sooner or later.

**Comment by ghost** [comment]
This is what I've done so far: [download](http://www.darthwound.net/linux/EquiluxCinnamon_WIP.tar.xz)

As written in the file name, it's **work in progress**, not finished at all. But I don't know when I'll have time to play with Cinnamon again. And Cinnamon CSS is a mess. I never liked this DE and obviously it's not today that it's gonna change :D **Assets should be ok**, except `../misc/buttonbox.svg` that I made pink because I still don't know what is it. So, **hopefully only thing to finish is some parts of the CSS file**.

@psimacek could you try it and post some screenshots please? I know that it needs much much more work, but I would like to be sure of the current rendering because my Cinnamon session doesn't refresh the theme sometimes, as if it was blocked in some kind of cache...

**Comment by psimacek** [comment]
@DarthWound Thanks a lot! I'm sorry, I'll look at it on Sunday, because I'm not at home, where I have Cinnamon.

**Comment by ghost** [comment]
Don't thank me yet, Sunday you'll be disappointed as it's really not complete :laughing: 

But if you know CSS basics you're probably able to finish it, all you need is more spare time than me...

**Comment by psimacek** [comment]
Hi DarthWound, I did a short test and I found, that: Cinnamon Menu icon and categories are not visible. Icon of Redshift is lighter than others. Screenshot is here: https://imgur.com/a/K7LEH

Sorry I'm not able to play with CSS :(

**Comment by ghost** [comment]
Thank you, I'll look at it when I can.

**Comment by ddnexus** [comment]
What is the status of this Issue?

**Comment by ghost** [comment]
Sorry, I'm still too busy to make any progress on it currently.
As I don't use Cinnamon...

However you can try to work on what I've done [here](https://github.com/ddnexus/equilux-theme/issues/4#issuecomment-343434418).

**Comment by ddnexus** [comment]
I've just released the new version with the latest from upstream and a better REAME, so I was house-cleaning the issues section.

I am also too busy right now, so this one will stay open. Thanks.

**Comment by ddnexus** [comment]
Just published the latest... it should include the Cinnamon specific files. Please, let me know how it looks. Thanks

**Comment by ddnexus** [comment]
@psimacek: ?

**Comment by psimacek** [comment]
Hi, it's much more better. Some icons on the bottom panel are lighter and update manager has problem with color of font.
![cinnamon](https://user-images.githubusercontent.com/1787889/39408739-3d7c72e0-4bdb-11e8-8fdf-ec2f5a5ff82d.png)

**Comment by ddnexus** [comment]
I could finally find a bit of time to update the theme. I hope cinnamon is ok now.
