### ISSUE TITLE
GDM Theme installation broke my gnome shell

### ISSUE THREAD

**Issue by michalzubkowicz** [ddnexus/Flat-Plat-Equilux#9]
After running command on Debian Stretch:
```
  GTK_THEME=$(gsettings get org.gnome.desktop.interface gtk-theme | sed "s/'//g")
  sudo ln -svb /usr/share{/themes/$GTK_THEME,}/gnome-shell/gnome-shell-theme.gresource
```
GDM won't start anymore. I had to restore backup file from /usr/share/gnome/shell/gnome-shell-theme.gresource~ to usr/share/gnome/shell/gnome-shell-theme.gresource

First problem is that command assumes that current theme is equilux, but event after change first gnome is  starting without a windows

**Comment by ddnexus** [comment]
Sorry for the accident. It would be nice if you can give me the detailed steps to reproduce the problem, so I could understand what happened and eventually fix or add one more warning. Thanks.

**Comment by michalzubkowicz** [comment]
Just run this command when another theme is enabled. It should broke your gnome shell ;) 

Second problem is that after properly enabling this gdm theme, gnome shell is not starting. Maybe you can point me where search for errors so I can reenable it again and check. In syslog and .xsession-errors I didn't find anything related.

**Comment by ddnexus** [comment]
oh... I see. Actually it is written in the README in the first point of the GDM installation: "1. Activate the Equilux Theme variant you want to install", but i should put a big warning there, because people may not know the consequences of that requirement. Besides, maybe I may also change the command so it will check what is the selected theme.

Could you check whether the link (or the 2 links if you are on 3.26) are pointing to the right file?

**Comment by nana-4** [comment]
@ddnexus I'm not sure if it relates to this problem, but IMO it is quite dangerous to use `ln -s` for changing GDM theme. For example, after installing GDM theme using `ln -s`, if you move or delete `/usr/share/themes/$GTK_THEME` directory, `/usr/share/gnome-shell/gnome-shell-theme.gresource` becomes a **broken symlink**. That means breaking the gnome-shell/gdm.

So, I recommend using `cp` or `mv` instead of `ln -s`. Please refer also my [GDM Theme wiki](https://github.com/nana-4/materia-theme/wiki/GDM-Theme).

**Comment by ddnexus** [comment]
You are right! Not all people are freaks like me, that never delete the only theme they use! :)
I will change the README and it is probably better just pointing the section to your documentation.
Thank you!

**Comment by nana-4** [comment]
@ddnexus You're welcome! :)

**Comment by ddnexus** [comment]
Linked the GDM installation to upstream
